### ISSUE TITLE
关于所采用的数据集字段类型

### ISSUE THREAD

**Issue by braid123** [PolarisRisingWar/rgb-experiment#2]
请问一下，代码中所使用的数据集都必须是x, y, edge_index类型的吗？可是有的数据集比如Elliptic目前发布的只有elliptic_txs_classes，elliptic_txs_features，elliptic_txs_edgelist三种类型，也好像没看到转化的代码？请问您是怎么解决这一问题的？

**Comment by PolarisRisingWar** [comment]
elliptic这个是我们组别的同学帮忙做过转换的。我不太了解具体的做法，你可以尝试把它也直接修改成x y edgeindex的形式。就是，据我所了解，一般特征标签（当然我的这种形式就只能应用于单标签情况）邻接矩阵是构成一个同质图的核心部分，不管是什么图，都应该可以转变成这种形式的。
